{{- $namespace := .Release.Namespace }}
{{- range .Values.microservices }}
{{- $name := .name  }}
{{- with .secrets }}
{{- if not ( lookup "v1" "Secret" $namespace .name ) }}

---

apiVersion: v1
data:
  {{- range $key, $value := .data }}
  {{ $key }}: {{ $value }}
  {{- end }}
kind: Secret
metadata:
  name: {{ .name }}
  {{- $data := dict "root" . "name" $name }}
  {{- include "template.labels" $data | indent 2 }}
type: Opaque
{{- end }}
{{- end }}
{{- end }}