{{- $namespace := .Release.Namespace }}
{{- range .Values.microservices }}
{{- $name := .name  }}
{{- with .horizontalpodautoscaler }}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name | default $name }}
  {{- $data := dict "root" . "name" $name }}
  {{- include "template.labels" $data | indent 2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{  .deployname | default $name }}
  minReplicas: {{ .minReplicas | default 1 }}
  maxReplicas: {{ .maxReplicas | default 5 }}
  {{- if .targetCPUUtilizationPercentage }}
  targetCPUUtilizationPercentage: {{.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- with .metrics }}
  metrics:
    {{- if .targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}