apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservices.demoapp2.name }}
  labels:
    run: {{ .Values.microservices.demoapp2.name }}
spec:
  type: {{ .Values.microservices.demoapp2.service.type }}
  ports:
  - port: {{ .Values.microservices.demoapp2.containerPort }}
    targetPort: {{ .Values.microservices.demoapp2.service.port }}
    protocol: TCP
    name: http
