apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.microservices.demoapp1.name }}
#  namespace: demoapp1
spec:
  replicas: {{ .Values.microservices.demoapp1.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.microservices.demoapp1.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.microservices.demoapp1.name }}
    spec:
      containers:
      - name: {{ .Values.microservices.demoapp1.name }}
        image: {{ .Values.microservices.demoapp1.image }}:{{ .Values.microservices.demoapp1.version }}
        ports:
        - containerPort: {{ .Values.microservices.demoapp1.containerPort }}
        readinessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.microservices.demoapp1.containerPort }}
          initialDelaySeconds: {{ .Values.microservices.demoapp1.probe.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.microservices.demoapp1.probe.readiness.periodSeconds }}
          failureThreshold: {{ .Values.microservices.demoapp1.probe.readiness.failureThreshold }}
        livenessProbe:
          httpGet:
            path: /index.html
            port: {{ .Values.microservices.demoapp1.containerPort }}
          initialDelaySeconds: {{ .Values.microservices.demoapp1.probe.liveness.initialDelaySeconds }}
  minReadySeconds: {{ .Values.microservices.demoapp1.minReadySeconds }}
  revisionHistoryLimit: {{ .Values.microservices.demoapp1.revisionHistoryLimit }}
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      steps:
      - setWeight: 20
      - pause:
          duration: 1m # 1 minute
      - setWeight: 40
      - pause:
          duration: 1m # 1 minute
      - setWeight: 60
      - pause:
          duration: 1m # 1 minute
      - setWeight: 80
      - pause:
          duration: 1m # 1 minute
      - setWeight: 100
      - pause: {} # pause indefinitely
