{{- range .Values.microservices }}
{{- $name := .name  }}
{{- with .ingress}}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name | default $name }}
  {{- $data := dict "root" . "name" $name }}
  {{- include "template.labels" $data | indent 2 }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- with .rules }}
  rules:
    {{- range . }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .svcname }}
                port:
                  number: {{ .svcport | default 80 }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
