{{- range .Values.microservices }}
{{- $name := .name }}
{{- with .deployment912839182}}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name | default $name }}
  {{- $data := dict "root" . "name" $name }}
  {{- include "template.labels" $data | indent 2 }}
spec:
  {{- if .minReadySeconds }}
  minReadySeconds: {{ .minReadySeconds }}
  {{- end }}
  {{- if .progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ .progressDeadlineSeconds }}
  {{- end }}
  {{- if .revisionHistoryLimit }}
  revisionHistoryLimit: {{ .revisionHistoryLimit }}
  {{- end }}
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .name | default $name }}
      version: {{ .version | default "v1" }}
    {{- with .matchLabels }}
      {{- range $key, $value := . }}
      {{ $key }}: {{ $value }}
      {{- end }}
    {{- end }}
  {{- if .strategy }}
  strategy:
    rollingUpdate:
      maxSurge: {{ default "25%" .strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ default "25%" .strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  {{- end }}
  template:
    metadata:
      {{- include "template.labels" $data | indent 6 }}
    spec:
      {{- with .initContainers }}
      initContainers:
      {{- range . }}
      {{- with .command }}
      - command:
      {{- range . }}
        - {{.}}
      {{- end }}
      {{- end }}
        image: {{ .image }}
        {{- include "template.securityContext" . | indent 8 }}
        name: {{default $name .name }}
        {{- with .volumeMounts  }}
        volumeMounts:
        {{- range . }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
        {{- end }}
        {{- end }} 
      {{- end }}
    {{- end }}

      {{- with .serviceAccountName}}
      serviceAccountName: {{ .serviceAccountName }}
      {{- end }} 
      containers:
      {{- include "template.environment" . | indent 6 }}
        image: {{ .image }}
        {{- with .command }}
        command:
        {{- range . }}
          - {{.}}
        {{- end }}
        {{- end }}
        imagePullPolicy: Always
        name: {{ .name | default $name }}
        {{- include "template.ports" . | indent 8}}
        {{- include "template.securityContext" . | indent 8 }}
        {{- with .resources }}
        resources:
          {{- with .limits }}
          limits:
            cpu: {{ .cpu }}
            memory: {{ .memory }}
          {{- end }}
          {{- with .requests }}
          requests:
            cpu: {{ .cpu }}
            memory: {{ .memory }}
          {{- end }}
        {{- end }}
        {{- with .volumeMounts  }}
        volumeMounts:
        {{- range . }}
          - mountPath: {{ .mountPath }}
            name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- include "template.startupProbe" . | indent 8 }}
        {{- include "template.livenessProbe" . | indent 8 }}
        {{- include "template.readinessProbe" . | indent 8 }}
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .volumes  }}
      volumes:
      {{- range . }}
        {{- if .hostPath }}
        - hostPath:
            path: {{ .hostPath.path }}
            type: ""
          name: {{ .name }}
        {{- else }}
        {{- if .persistentVolumeClaim }}
        - persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
          name: {{ .name }}
        {{- else }}
        {{- if .configMap }}
        - configMap:
            defaultMode:  {{ .configMap.defaultMode }}
          {{- with .configMap.items }}
            items:
            {{- range . }}
            - key: {{ .key }}
              path:  {{ .path }}
            {{- end }}
            {{- end }}
            name:  {{ .name }}
            optional: false
          name:  {{ .name }}
        {{- else }}
        - emptyDir: {}
          name: {{ .name }}
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}

{{- end }}
{{- end }}
